import streamlit as st
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
import torch
from newspaper import Article
import time

# 1. LOAD THE AI MODEL
@st.cache_resource
def load_model_and_tokenizer():
    model_name = "google/flan-t5-small"
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name, low_cpu_mem_usage=True)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    return model, tokenizer

model, tokenizer = load_model_and_tokenizer()

# 2. SESSION STATE
if "history" not in st.session_state:
    st.session_state.history = []

# 3. UI DESIGN
st.set_page_config(page_title="News Summarizer", page_icon="📑", layout="wide")

with st.sidebar:
    st.title("📜 Summary History")
    if not st.session_state.history:
        st.write("No summaries yet.")
    else:
        for idx, h in enumerate(reversed(st.session_state.history)):
            st.write(f"{len(st.session_state.history) - idx}. {h}")
    
    st.divider()
    if st.button("Clear History"):
        st.session_state.history = []
        st.rerun()

st.title("📑 News Summarizer", help="High-precision AI News Analysis.")
st.write("Generating structured, professional intelligence reports.")

url = st.text_input("Paste any news article URL here:", placeholder="https://www.ndtv.com/...")

if st.button("Generate Summary"):
    if url:
        start_time = time.time()
        status_text = st.empty()
        status_text.info("⚡ Rapid Extraction Active...")
        
        try:
            # 4. LIGHTWEIGHT EXTRACTION
            article = Article(url, request_timeout=10)
            article.download()
            article.parse()
            
            raw_text = article.text
            article_title = article.title if article.title else "News Update"
            
            if len(raw_text) < 200:
                st.error("Extraction failed. Site might be blocking access.")
            else:
                status_text.info("🧠 Performing Semantic Precision Analysis...")
                
                # 5. STRUCTURED AI LOGIC
                input_prompt = f"Identify the top 10 unique facts from this text and explain them clearly: {raw_text[:1200]}"
                inputs = tokenizer(input_prompt, return_tensors="pt", truncation=True, max_length=512)
                
                with torch.no_grad():
                    outputs = model.generate(
                        inputs["input_ids"], 
                        max_length=512,        
                        min_length=300,        
                        do_sample=True,         
                        top_p=0.8,              
                        temperature=0.6,        
                        repetition_penalty=4.5, 
                        no_repeat_ngram_size=4, 
                        early_stopping=True
                    )
                
                summary = tokenizer.decode(outputs[0], skip_special_tokens=True)
                
                # 6. QUALITY FORMATTING
                lines = [line.strip() for line in summary.split(". ") if len(line) > 20]
                bullet_points = ""
                for line in lines[:12]:
                    bullet_points += f"• {line}.\n\n"

                bottom_line = lines[0] if lines else "Analysis complete."

                final_report = f"""
📰 Summary: {article_title} ({time.strftime("%B %d, %Y")})

{bullet_points}

📌 Bottom line
The article highlights key regional dynamics:
• {bottom_line}.
• Critical humanitarian and geopolitical implications.
• Urgent need for international monitoring.
                """

                # Update History
                history_label = f"{article_title[:40]}..."
                if history_label not in st.session_state.history:
                    st.session_state.history.append(history_label)

                status_text.empty()
                st.success(f"Analysis Complete! ({round(time.time() - start_time, 2)}s)")
                
                st.markdown(f"### {article_title}")
                st.markdown(final_report) 
                
                # 7. ENHANCED DOWNLOAD FILE QUALITY
                download_content = f"""==================================================
              NEWS ANALYSIS REPORT
==================================================
TITLE: {article_title.upper()}
SOURCE: {url}
GEN-DATE: {time.strftime("%Y-%m-%d %H:%M:%S")}
--------------------------------------------------

{final_report}

--------------------------------------------------
DISCLAIMER: This report is generated by an AI model.
==================================================
                """

                st.download_button(
                    label="💾 Download Professional Report", 
                    data=download_content, 
                    file_name=f"News_Report_{int(time.time())}.txt",
                    mime="text/plain"
                )

        except Exception as e:
            st.error(f"Error processing the request: {e}")
    else:
        st.warning("Please paste a URL first!")