import streamlit as st
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
import torch
from newspaper import Article
import time

# 1. LOAD THE AI MODEL
@st.cache_resource
def load_model_and_tokenizer():
    model_name = "google/flan-t5-small"
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name, low_cpu_mem_usage=True)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    return model, tokenizer

model, tokenizer = load_model_and_tokenizer()

# 2. SESSION STATE
if "history" not in st.session_state:
    st.session_state.history = []

# 3. UI DESIGN
st.set_page_config(page_title="News Summarizer", page_icon="📑", layout="wide")

with st.sidebar:
    st.title("📜 Summary History")
    if not st.session_state.history:
        st.write("No summaries yet.")
    else:
        for idx, h in enumerate(reversed(st.session_state.history)):
            st.write(f"{len(st.session_state.history) - idx}. {h}")
    
    st.divider()
    if st.button("Clear History"):
        st.session_state.history = []
        st.rerun()

st.title("📑 News Summarizer", help="High-precision AI News Analysis.")
st.write("Generating structured, accurate 15-line reports.")

url = st.text_input("Paste any news article URL here:", placeholder="https://www.ndtv.com/...")

if st.button("Generate Summary"):
    if url:
        start_time = time.time()
        status_text = st.empty()
        status_text.info("⚡ Rapid Extraction Active...")
        
        try:
            # 4. LIGHTWEIGHT EXTRACTION
            article = Article(url, request_timeout=10)
            article.download()
            article.parse()
            
            raw_text = article.text
            article_title = article.title if article.title else "News Update"
            
            if len(raw_text) < 200:
                st.error("Extraction failed. The site may be blocking access.")
            else:
                status_text.info("🧠 Performing Semantic Precision Analysis...")
                
                # 5. PRECISION AI LOGIC
                # We refine the prompt to focus strictly on facts in the text
                input_prompt = f"Summarize the following article accurately in exactly 15 detailed bullet points. Focus only on the facts provided: {raw_text[:1300]}"
                inputs = tokenizer(input_prompt, return_tensors="pt", truncation=True, max_length=512)
                
                with torch.no_grad():
                    outputs = model.generate(
                        inputs["input_ids"], 
                        max_length=512,        
                        min_length=320,        # Increased slightly for better depth
                        do_sample=True,         
                        top_p=0.85,             # Reduced slightly to keep it more "grounded" and less random
                        temperature=0.7,        # Added temperature to balance creativity and accuracy
                        repetition_penalty=4.0, # Increased to prevent the looping seen in your images
                        no_repeat_ngram_size=4, # Harder blocking for 4-word sequences
                        early_stopping=True
                    )
                
                summary = tokenizer.decode(outputs[0], skip_special_tokens=True)
                
                # 6. QUALITY FORMATTING FOR UI AND DOWNLOAD
                # We turn the messy text into a clean bulleted report
                lines = summary.split(". ")
                clean_lines = [line.strip() + "." for line in lines if len(line) > 15]
                
                # Ensure we have a bulleted structure for the "Gemini/ChatGPT" look
                report_body = "\n\n• ".join(clean_lines[:15]) # Limit to 15 best points
                if not report_body.startswith("• "):
                    report_body = "• " + report_body

                # Create the Download Text with a professional header
                download_content = f"""
NEWS ANALYSIS REPORT
--------------------
TITLE: {article_title.upper()}
SOURCE: {url}
DATE: {time.strftime("%Y-%m-%d %H:%M:%S")}

SUMMARY:
{report_body}

--------------------
Generated by AI News Summarizer
                """

                # Update History
                history_label = f"{article_title[:40]}..."
                if history_label not in st.session_state.history:
                    st.session_state.history.append(history_label)

                status_text.empty()
                st.success(f"Analysis Complete! ({round(time.time() - start_time, 2)}s)")
                
                st.subheader(article_title)
                st.markdown(report_body) 
                
                # Improved download button
                st.download_button(
                    label="💾 Download Professional Report", 
                    data=download_content, 
                    file_name=f"News_Report_{int(time.time())}.txt",
                    mime="text/plain"
                )

        except Exception as e:
            st.error(f"Error: {e}")
    else:
        st.warning("Please paste a URL first!")