import json
import re
import requests
import trafilatura

from bs4 import BeautifulSoup
from urllib.parse import urlparse


# ============================================================
# HEADERS
# ============================================================

HEADERS_LIST = [
    {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/151.0.0.0 Safari/537.36"
        ),
        "Accept": (
            "text/html,application/xhtml+xml,application/xml;"
            "q=0.9,image/avif,image/webp,*/*;q=0.8"
        ),
        "Accept-Language": "en-US,en;q=0.9",
        "Referer": "https://www.google.com/",
    },
    {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 "
            "Chrome/131.0.0.0 Safari/537.36"
        ),
        "Accept": "text/html,application/xhtml+xml",
        "Accept-Language": "en-US,en;q=0.9",
    },
]


# ============================================================
# CLEAN TEXT
# ============================================================

def clean_text(text):
    if not text:
        return ""

    text = re.sub(r"\r\n?", "\n", text)

    lines = []

    for line in text.splitlines():
        line = re.sub(r"\s+", " ", line).strip()

        if line:
            lines.append(line)

    text = "\n\n".join(lines)

    return text.strip()


# ============================================================
# CHECK IF PAGE IS AN ERROR PAGE
# ============================================================

def is_error_page(text):
    """
    Prevent CloudFront / 403 / access-denied pages
    from being sent to Gemini.
    """

    if not text:
        return True

    lower = text.lower()

    error_patterns = [
        "403 forbidden",
        "404 not found",
        "access denied",
        "request blocked",
        "request could not be satisfied",
        "the request could not be satisfied",
        "cloudfront",
        "generated by cloudfront",
        "amazon cloudfront",
        "error from cloudfront",
        "permission denied",
        "service unavailable",
        "502 bad gateway",
        "503 service unavailable",
        "gateway timeout",
        "temporarily unavailable",
        "too many requests",
    ]

    matches = sum(
        1 for pattern in error_patterns
        if pattern in lower
    )

    # If several error indicators appear, reject the page.
    if matches >= 1 and len(text) < 5000:
        return True

    return False


# ============================================================
# VALIDATE ARTICLE TEXT
# ============================================================

def is_valid_article(text):
    if not text:
        return False

    text = clean_text(text)

    if len(text) < 500:
        return False

    if is_error_page(text):
        return False

    # News articles usually contain multiple sentences.
    sentences = re.split(r"[.!?]\s+", text)

    if len(sentences) < 5:
        return False

    return True


# ============================================================
# JSON-LD EXTRACTION
# ============================================================

def extract_jsonld_article(html):
    """
    Many news websites expose article text through
    JSON-LD structured data.
    """

    try:
        soup = BeautifulSoup(html, "html.parser")

        scripts = soup.find_all(
            "script",
            type="application/ld+json"
        )

        for script in scripts:

            try:
                data = json.loads(
                    script.string or script.get_text()
                )
            except Exception:
                continue

            objects = []

            if isinstance(data, dict):
                objects.append(data)

                if "@graph" in data:
                    graph = data["@graph"]

                    if isinstance(graph, list):
                        objects.extend(graph)

            elif isinstance(data, list):
                objects.extend(data)

            for item in objects:

                if not isinstance(item, dict):
                    continue

                article_body = item.get("articleBody")

                if article_body:
                    article_body = clean_text(article_body)

                    if is_valid_article(article_body):
                        return article_body

    except Exception:
        pass

    return ""


# ============================================================
# META DESCRIPTION FALLBACK
# ============================================================

def extract_meta_text(html):
    try:
        soup = BeautifulSoup(html, "html.parser")

        candidates = []

        # Description
        for tag in soup.find_all(
            "meta",
            attrs={"name": "description"}
        ):
            content = tag.get("content")

            if content:
                candidates.append(content)

        # OpenGraph description
        for tag in soup.find_all(
            "meta",
            attrs={"property": "og:description"}
        ):
            content = tag.get("content")

            if content:
                candidates.append(content)

        text = "\n".join(candidates)

        return clean_text(text)

    except Exception:
        return ""


# ============================================================
# DIRECT EXTRACTION
# ============================================================

def extract_with_requests(url):

    for headers in HEADERS_LIST:

        try:

            response = requests.get(
                url,
                headers=headers,
                timeout=20,
                allow_redirects=True
            )

            # NEVER process obvious blocking responses
            if response.status_code in [
                401,
                403,
                404,
                429,
                500,
                502,
                503,
                504
            ]:
                continue

            if response.status_code != 200:
                continue

            html = response.text

            if not html:
                continue

            # ------------------------------------------------
            # METHOD 1: Trafilatura
            # ------------------------------------------------

            text = trafilatura.extract(
                html,
                include_comments=False,
                include_tables=False,
                include_links=False,
                favor_precision=False,
                favor_recall=True
            )

            text = clean_text(text)

            if is_valid_article(text):
                return text

            # ------------------------------------------------
            # METHOD 2: JSON-LD
            # ------------------------------------------------

            text = extract_jsonld_article(html)

            if is_valid_article(text):
                return text

            # ------------------------------------------------
            # METHOD 3: BeautifulSoup article tag
            # ------------------------------------------------

            soup = BeautifulSoup(
                html,
                "html.parser"
            )

            for element in soup([
                "script",
                "style",
                "noscript",
                "nav",
                "footer",
                "header",
                "aside",
                "form",
                "svg"
            ]):
                element.decompose()

            article = soup.find("article")

            if article:

                text = article.get_text(
                    separator="\n",
                    strip=True
                )

                text = clean_text(text)

                if is_valid_article(text):
                    return text

            # ------------------------------------------------
            # METHOD 4: Paragraph extraction
            # ------------------------------------------------

            paragraphs = soup.find_all("p")

            paragraph_texts = []

            for p in paragraphs:

                paragraph = p.get_text(
                    " ",
                    strip=True
                )

                paragraph = clean_text(paragraph)

                if len(paragraph) > 40:
                    paragraph_texts.append(paragraph)

            text = "\n\n".join(
                paragraph_texts
            )

            text = clean_text(text)

            if is_valid_article(text):
                return text

        except Exception:
            continue

    return ""


# ============================================================
# JINA READER
# ============================================================

def extract_with_jina(url):

    try:

        jina_url = "https://r.jina.ai/" + url

        response = requests.get(
            jina_url,
            headers={
                "User-Agent": (
                    "Mozilla/5.0 "
                    "NewsSummarizer/1.0"
                ),
                "Accept": "text/plain"
            },
            timeout=40
        )

        if response.status_code != 200:
            return ""

        text = response.text

        text = clean_text(text)

        # IMPORTANT:
        # Jina may return the publisher's 403 page.
        # Never send that to Gemini.
        if is_error_page(text):
            return ""

        if is_valid_article(text):
            return text

    except Exception:
        pass

    return ""


# ============================================================
# MAIN EXTRACTION FUNCTION
# ============================================================

def extract_article(url):

    url = url.strip()

    if not url:
        return None

    # --------------------------------------------------------
    # URL VALIDATION
    # --------------------------------------------------------

    try:

        parsed = urlparse(url)

        if parsed.scheme not in (
            "http",
            "https"
        ):
            return None

        if not parsed.netloc:
            return None

    except Exception:
        return None

    # --------------------------------------------------------
    # METHOD 1
    # Direct requests + Trafilatura
    # --------------------------------------------------------

    text = extract_with_requests(url)

    if text:
        return text

    # --------------------------------------------------------
    # METHOD 2
    # Jina Reader
    # --------------------------------------------------------

    text = extract_with_jina(url)

    if text:
        return text

    # Nothing reliable was extracted
    return None