import json
import re
import urllib.parse
from bs4 import BeautifulSoup
import feedparser
import trafilatura
from curl_cffi import requests as curl_requests


def _clean_text(text: str) -> str:
    if not text:
        return ""
    text = re.sub(r"\n\s*\n+", "\n\n", text)
    return text.strip()


def _is_error_payload(text: str) -> bool:
    """Verifies that the content is real article prose and not a WAF error screen."""
    if not text or len(text.strip()) < 250:
        return True
    lower = text.lower()
    error_markers = [
        "403 forbidden",
        "cloudfront",
        "request could not be satisfied",
        "access denied",
        "attention required",
        "robot or human",
        "enable javascript",
        "generated by cloudfront",
        "block by cloudflare",
        "just a moment...",
    ]
    return any(marker in lower for marker in error_markers)


def _extract_from_json_ld(soup: BeautifulSoup) -> str:
    """Extracts article body directly from JSON-LD schema blocks."""
    for script in soup.find_all("script", type="application/ld+json"):
        if not script.string:
            continue
        try:
            data = json.loads(script.string.strip())
            items = data if isinstance(data, list) else [data]
            for item in items:
                if isinstance(item, dict):
                    if item.get("articleBody"):
                        return item["articleBody"].strip()
                    for graph_item in item.get("@graph", []):
                        if isinstance(graph_item, dict) and graph_item.get("articleBody"):
                            return graph_item["articleBody"].strip()
        except Exception:
            continue
    return ""


def _extract_soup_paragraphs(soup: BeautifulSoup) -> str:
    """Extracts clean article paragraphs."""
    for tag in soup(["script", "style", "nav", "header", "footer", "aside", "form"]):
        tag.decompose()

    container = soup.find(
        "div",
        class_=re.compile(
            r"(story-details|full-details|story_details|ie-content|art-content|wp-block-post-content|article-body|storycontent)",
            re.IGNORECASE,
        ),
    ) or soup.find(["article", "main"])

    target = container if container else soup
    paragraphs = [
        p.get_text(" ", strip=True)
        for p in target.find_all("p")
        if len(p.get_text(strip=True)) > 35
        and not p.get_text(strip=True).startswith(
            ("Also Read", "Click here", "Subscribe", "Explained |", "Follow us on")
        )
    ]
    return "\n\n".join(paragraphs) if len(paragraphs) >= 2 else ""


def _parse_html_payload(html: str) -> str:
    """Extracts clean text using JSON-LD, Trafilatura, and BeautifulSoup."""
    if not html or _is_error_payload(html):
        return ""

    soup = BeautifulSoup(html, "html.parser")

    # 1. JSON-LD schema
    json_ld = _extract_from_json_ld(soup)
    if json_ld and not _is_error_payload(json_ld):
        return _clean_text(json_ld)

    # 2. Trafilatura
    traf = trafilatura.extract(
        html,
        include_comments=False,
        include_tables=False,
        no_fallback=False,
    )
    if traf and not _is_error_payload(traf):
        return _clean_text(traf)

    # 3. DOM fallback
    dom = _extract_soup_paragraphs(soup)
    if dom and not _is_error_payload(dom):
        return _clean_text(dom)

    return ""


def _fetch_indian_express_via_feed_and_syndication(url: str) -> str:
    """
    Indian Express maintains completely unblocked RSS / Mobile syndication
    feeds that are exempt from Cloudflare Turnstile blocks.
    """
    clean_target = url.split("?")[0].rstrip("/")
    slug_part = clean_target.split("/")[-1]

    # Method 1: Feedparser matching from IE section feeds
    section = "article"
    parts = clean_target.split("/")
    if len(parts) >= 5:
        section = parts[4]  # e.g., entertainment, opinion, world, india

    rss_urls = [
        f"https://indianexpress.com/section/{section}/feed/",
        "https://indianexpress.com/feed/",
    ]

    for rss in rss_urls:
        try:
            feed = feedparser.parse(rss)
            for entry in feed.entries:
                if slug_part in entry.link or entry.link.rstrip("/") == clean_target:
                    content_raw = entry.get("content", [{}])[0].get("value", "") or entry.get("summary", "")
                    if content_raw:
                        soup = BeautifulSoup(content_raw, "html.parser")
                        paragraphs = [p.get_text(strip=True) for p in soup.find_all("p") if len(p.get_text(strip=True)) > 25]
                        if paragraphs:
                            return _clean_text("\n\n".join(paragraphs))
                        text = soup.get_text(" ", strip=True)
                        if len(text) > 250:
                            return _clean_text(text)
        except Exception:
            pass

    # Method 2: Google Search text-cache mirror
    try:
        gcache = f"https://webcache.googleusercontent.com/search?q=cache:{clean_target}&strip=1"
        resp = curl_requests.get(gcache, timeout=8)
        if resp.status_code == 200:
            extracted = _parse_html_payload(resp.text)
            if extracted:
                return extracted
    except Exception:
        pass

    # Method 3: JSON Content Bridge
    try:
        encoded = urllib.parse.quote(clean_target, safe="")
        bridge_url = f"https://api.allorigins.win/get?url={encoded}"
        resp = curl_requests.get(bridge_url, timeout=10)
        if resp.status_code == 200:
            payload = resp.json().get("contents", "")
            extracted = _parse_html_payload(payload)
            if extracted:
                return extracted
    except Exception:
        pass

    return ""


def extract_article(url: str) -> str:
    clean_url = url.strip()

    # Special unblocked syndication route for Indian Express
    if "indianexpress.com" in clean_url:
        ie_text = _fetch_indian_express_via_feed_and_syndication(clean_url)
        if ie_text:
            return ie_text

    # Standard direct fetch for other websites (The Hindu, NDTV, BBC, TOI)
    try:
        resp = curl_requests.get(
            clean_url,
            impersonate="chrome120",
            timeout=10,
            headers={
                "Referer": "https://www.google.com/",
                "Accept-Language": "en-US,en;q=0.9",
            },
        )
        if resp.status_code == 200:
            extracted = _parse_html_payload(resp.text)
            if extracted:
                return extracted
    except Exception:
        pass

    # Trafilatura standard fetch
    try:
        html = trafilatura.fetch_url(clean_url)
        if html:
            extracted = _parse_html_payload(html)
            if extracted:
                return extracted
    except Exception:
        pass

    return ""