import json
import re
import urllib.parse
from bs4 import BeautifulSoup
import trafilatura
from curl_cffi import requests as curl_requests


def _clean_text(text: str) -> str:
    if not text:
        return ""
    text = re.sub(r"\n\s*\n+", "\n\n", text)
    return text.strip()


def _is_error_payload(text: str) -> bool:
    """Verifies that the content is real article prose and not a WAF error screen."""
    if not text or len(text.strip()) < 250:
        return True
    lower = text.lower()
    error_markers = [
        "403 forbidden",
        "cloudfront",
        "request could not be satisfied",
        "access denied",
        "attention required",
        "robot or human",
        "enable javascript",
        "generated by cloudfront",
        "block by cloudflare",
        "just a moment...",
    ]
    return any(marker in lower for marker in error_markers)


def _extract_from_json_ld(soup: BeautifulSoup) -> str:
    """Extracts article body directly from JSON-LD schema blocks."""
    for script in soup.find_all("script", type="application/ld+json"):
        if not script.string:
            continue
        try:
            data = json.loads(script.string.strip())
            items = data if isinstance(data, list) else [data]
            for item in items:
                if isinstance(item, dict):
                    if item.get("articleBody"):
                        return item["articleBody"].strip()
                    for graph_item in item.get("@graph", []):
                        if isinstance(graph_item, dict) and graph_item.get("articleBody"):
                            return graph_item["articleBody"].strip()
        except Exception:
            continue
    return ""


def _extract_soup_paragraphs(soup: BeautifulSoup) -> str:
    """Extracts clean article paragraphs."""
    for tag in soup(["script", "style", "nav", "header", "footer", "aside", "form"]):
        tag.decompose()

    container = soup.find(
        "div",
        class_=re.compile(
            r"(story-details|full-details|story_details|ie-content|art-content|wp-block-post-content|article-body|storycontent)",
            re.IGNORECASE,
        ),
    ) or soup.find(["article", "main"])

    target = container if container else soup
    paragraphs = [
        p.get_text(" ", strip=True)
        for p in target.find_all("p")
        if len(p.get_text(strip=True)) > 35
        and not p.get_text(strip=True).startswith(
            ("Also Read", "Click here", "Subscribe", "Explained |", "Follow us on")
        )
    ]
    return "\n\n".join(paragraphs) if len(paragraphs) >= 2 else ""


def _parse_html_payload(html: str) -> str:
    """Extracts clean text using JSON-LD, Trafilatura, and BeautifulSoup."""
    if not html or _is_error_payload(html):
        return ""

    soup = BeautifulSoup(html, "html.parser")

    # 1. JSON-LD schema (most accurate and ad-free)
    json_ld = _extract_from_json_ld(soup)
    if json_ld and not _is_error_payload(json_ld):
        return _clean_text(json_ld)

    # 2. Trafilatura
    traf = trafilatura.extract(
        html,
        include_comments=False,
        include_tables=False,
        no_fallback=False,
    )
    if traf and not _is_error_payload(traf):
        return _clean_text(traf)

    # 3. DOM fallback
    dom = _extract_soup_paragraphs(soup)
    if dom and not _is_error_payload(dom):
        return _clean_text(dom)

    return ""


def _fetch_via_relays(url: str) -> str:
    """Tunnels the request through external relays whose IPs are not blocked by CloudFront."""
    clean_target = url.split("?")[0].rstrip("/")
    encoded_url = urllib.parse.quote(clean_target, safe="")

    # Relay 1: AllOrigins JSON bridge (Cloudflare-hosted, extracts page off-datacenter)
    try:
        bridge_url = f"https://api.allorigins.win/get?url={encoded_url}"
        resp = curl_requests.get(bridge_url, timeout=12)
        if resp.status_code == 200:
            payload = resp.json().get("contents", "")
            extracted = _parse_html_payload(payload)
            if extracted:
                return extracted
    except Exception:
        pass

    # Relay 2: CorsProxy gateway
    try:
        cors_url = f"https://corsproxy.io/?{clean_target}"
        resp = curl_requests.get(
            cors_url,
            impersonate="chrome120",
            timeout=12,
            headers={"Accept": "text/html,application/xhtml+xml"}
        )
        if resp.status_code == 200:
            extracted = _parse_html_payload(resp.text)
            if extracted:
                return extracted
    except Exception:
        pass

    # Relay 3: Google AMP Project CDN Mirror
    try:
        stripped_domain = clean_target.replace("https://", "").replace("http://", "")
        amp_cdn = f"https://cdn.ampproject.org/c/s/{stripped_domain}"
        resp = curl_requests.get(
            amp_cdn,
            impersonate="chrome120",
            timeout=10,
            headers={"User-Agent": "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36"}
        )
        if resp.status_code == 200:
            extracted = _parse_html_payload(resp.text)
            if extracted:
                return extracted
    except Exception:
        pass

    return ""


def extract_article(url: str) -> str:
    clean_url = url.strip()

    # Step 1: For Indian Express or known firewalled outlets, tunnel via relays immediately
    if "indianexpress.com" in clean_url:
        relay_text = _fetch_via_relays(clean_url)
        if relay_text:
            return relay_text

    # Step 2: Standard direct fetch for other websites (The Hindu, NDTV, BBC, TOI)
    try:
        resp = curl_requests.get(
            clean_url,
            impersonate="chrome120",
            timeout=10,
            headers={
                "Referer": "https://www.google.com/",
                "Accept-Language": "en-US,en;q=0.9",
            },
        )
        if resp.status_code == 200:
            extracted = _parse_html_payload(resp.text)
            if extracted:
                return extracted
    except Exception:
        pass

    # Step 3: Trafilatura standard fetch
    try:
        html = trafilatura.fetch_url(clean_url)
        if html:
            extracted = _parse_html_payload(html)
            if extracted:
                return extracted
    except Exception:
        pass

    # Step 4: Final relay attempt for any other site that might have blocked the direct request
    fallback_text = _fetch_via_relays(clean_url)
    if fallback_text:
        return fallback_text

    return ""